"""add agent fields

Revision ID: 727710f71b1d
Revises: add_incident_id_media
Create Date: 2026-01-29 16:50:58.946162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727710f71b1d'
down_revision: Union[str, Sequence[str], None] = 'add_incident_id_media'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT name FROM sqlite_master 
        WHERE type='table' AND name LIKE '_alembic_tmp_%'
    """))
    temp_tables = [row[0] for row in result]
    
    for table in temp_tables:
        op.execute(f'DROP TABLE IF EXISTS {table}')
    
    # ### commands auto generated by Alembic - please adjust! ###
    # ... rest of your migration ...
    try:
        op.drop_table('member_ward_coverage')
    except:
        # Table doesn't exist, continue without error
        pass
    
    # Use batch mode for media table
    with op.batch_alter_table('media') as batch_op:
        batch_op.drop_constraint('fk_media_incident_id', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_media_incident_id_ref', 
            'incidents', 
            ['incident_id'], 
            ['id']
        )
    
    # Use batch mode for project_lga_coverage table
    with op.batch_alter_table('project_lga_coverage') as batch_op:
        batch_op.alter_column('state_coverage_id', nullable=False)
        batch_op.create_foreign_key(
            'fk_project_lga_coverage_state',
            'project_state_coverage', 
            ['state_coverage_id'], 
            ['id']
        )
    
    # Use batch mode for project_members table
    with op.batch_alter_table('project_members') as batch_op:
        batch_op.add_column(sa.Column('agent_code', sa.String(), nullable=True))
        batch_op.alter_column('status',
                            existing_type=sa.VARCHAR(length=7),
                            type_=sa.Enum('INVITED', 'ACTIVE', 'REMOVED', 'SUSPENDED',
                                        'DEACTIVATED', 'IDLE', name='projectmemberstatus'),
                            existing_nullable=False)
        # Note: We need to know the constraint name to drop it
        # Since it's None in the original, we'll skip dropping it and just drop the column
        # The foreign key will be automatically dropped when we drop the column
        batch_op.drop_column('ward_coverage_id')
    
    # Use batch mode for project_pu_coverage table
    with op.batch_alter_table('project_pu_coverage') as batch_op:
        batch_op.alter_column('ward_coverage_id', nullable=False)
        batch_op.create_foreign_key(
            'fk_project_pu_coverage_ward',
            'project_ward_coverage', 
            ['ward_coverage_id'], 
            ['id']
        )
    
    # Use batch mode for project_ward_coverage table
    with op.batch_alter_table('project_ward_coverage') as batch_op:
        batch_op.alter_column('lga_coverage_id', nullable=False)
        batch_op.create_foreign_key(
            'fk_project_ward_coverage_lga',
            'project_lga_coverage', 
            ['lga_coverage_id'], 
            ['id']
        )
    
    # Add column to projects table (this is simple, no batch needed)
    op.add_column('projects', sa.Column('agent_seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'agent_seq')
    
    # Use batch mode for project_ward_coverage table
    with op.batch_alter_table('project_ward_coverage') as batch_op:
        batch_op.drop_constraint('fk_project_ward_coverage_lga', type_='foreignkey')
        batch_op.alter_column('lga_coverage_id', nullable=True)
    
    # Use batch mode for project_pu_coverage table
    with op.batch_alter_table('project_pu_coverage') as batch_op:
        batch_op.drop_constraint('fk_project_pu_coverage_ward', type_='foreignkey')
        batch_op.alter_column('ward_coverage_id', nullable=True)
    
    # Use batch mode for project_members table
    with op.batch_alter_table('project_members') as batch_op:
        batch_op.add_column(sa.Column('ward_coverage_id', sa.VARCHAR(length=60), nullable=True))
        # Create a new foreign key constraint
        batch_op.create_foreign_key(
            'fk_project_members_ward',
            'project_ward_coverage', 
            ['ward_coverage_id'], 
            ['id']
        )
        batch_op.alter_column('status',
                            existing_type=sa.Enum('INVITED', 'ACTIVE', 'REMOVED', 'SUSPENDED',
                                                'DEACTIVATED', 'IDLE', name='projectmemberstatus'),
                            type_=sa.VARCHAR(length=7),
                            existing_nullable=False)
        batch_op.drop_column('agent_code')
    
    # Use batch mode for project_lga_coverage table
    with op.batch_alter_table('project_lga_coverage') as batch_op:
        batch_op.drop_constraint('fk_project_lga_coverage_state', type_='foreignkey')
        batch_op.alter_column('state_coverage_id', nullable=True)
    
    # Use batch mode for media table
    with op.batch_alter_table('media') as batch_op:
        batch_op.drop_constraint('fk_media_incident_id_ref', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_media_incident_id', 
            'incidents', 
            ['incident_id'], 
            ['id'], 
            ondelete='SET NULL'
        )
    
    op.create_table('member_ward_coverage',
                    sa.Column('member_id', sa.VARCHAR(
                        length=60), nullable=False),
                    sa.Column('ward_coverage_id', sa.VARCHAR(
                        length=60), nullable=True),
                    sa.Column('id', sa.VARCHAR(length=60), nullable=False),
                    sa.Column('created_at', sa.DATETIME(), nullable=False),
                    sa.Column('updated_at', sa.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['member_id'], ['project_members.id'], name='fk_member_ward_member'
                    ),
                    sa.ForeignKeyConstraint(['ward_coverage_id'], [
                        'project_ward_coverage.id'], name='fk_member_ward_ward'
                    ),
                    sa.PrimaryKeyConstraint('member_id', 'id'),
                    sa.UniqueConstraint('member_id', 'ward_coverage_id')
                    )
    # ### end Alembic commands ###