"""Incident attached to polling units

Revision ID: 790f9e004bec
Revises: 80e97b300b1d
Create Date: 2026-01-30 00:13:15.946920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790f9e004bec'
down_revision: Union[str, Sequence[str], None] = '80e97b300b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clean up temp tables
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_incidents')
    
    # 1. Add as nullable
    op.add_column('incidents', sa.Column('polling_unit_id', sa.String(length=60), nullable=True))
    
    # 2. Update with default value (choose one from project_pu_coverage)
    # This assumes you have at least one row in project_pu_coverage
    op.execute("""
        UPDATE incidents 
        SET polling_unit_id = (
            SELECT id FROM project_pu_coverage LIMIT 1
        )
        WHERE polling_unit_id IS NULL
    """)
    
    # 3. Use batch mode to make NOT NULL and add foreign key
    with op.batch_alter_table('incidents') as batch_op:
        batch_op.alter_column('polling_unit_id', nullable=False)
        batch_op.create_foreign_key(
            'fk_incidents_polling_unit_id',
            'project_pu_coverage', 
            ['polling_unit_id'], 
            ['id']
        )
        batch_op.drop_column('result_id')
    # ### end Alembic commands ###